[package]
name = "wasm-forth-runtime-tests"
version = "0.0.0"
edition = "2024"
publish = false

[[bin]]
name = "wasmtime-repl"
path = "src/wasmtime.rs"
required-features = ["wasmtime"]

[dependencies]
anyhow = "1.0.99"
ariadne = "0.4"
wasmtime = { version = "36.0.2", default-features = false, features = ["cranelift", "runtime"], optional = true }
